{
  imports = [
    ./packages.nix
    ./btop.nix
    ./bat.nix
    ./cursor.nix
    ./firefox.nix
    ./fonts.nix
    ./git.nix
    ./helix.nix
    ./hyprland.nix
    ./kitty.nix
    ./lazygit.nix
    ./mango.nix
    #./nvf.nix
    ./nixvim.nix
    ./rofi.nix
    ./starship.nix
    ./swaylock.nix
    ./tmux.nix
    ./waybar.nix
    ./yazi.nix
    ./zed.nix
    ./zsh.nix
  ];
}
